services:
  mysql:
    image: mysql:9.3.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    #      TZ: UTC
    #    command: --default-time-zone='+00:00'
    ports:
      - '3307:3307'
    expose:
      - 3307

volumes:
  mysql: